#+title: Chess Engine Docs

* 1. Bit Tricks
** static inline int count_bits(U64 bitboard);

  The function count_bits works using a trick with binary numbers.  When
  you subtract 1 from a binary number, it either clears bit 0 or clears
  the least significant set bit to set all downstream bits to 1.  When a
  bitwise AND is applied to the original number and that number minus 1,
  only the bits more significant than the least significant set bit
  remain the same and are preserved, while the least signficant set bit
  is cleared.  If we repeat this process until the number is 0 and count
  the number of times we use the bitwise AND, then we can count the
  number of bits without having to check every single bit.

** static inline int get_lsb_index(U64 bitboard);

  The function get_lsb_index finds the bit index of the least
  significant set bit.  The input must be greater than zero.  The
  function works by applying bitwise AND to the number provided and its
  negation.  The negation of a number is just the complement of that
  number plus one.  By definition, the least significant set bit is the
  first 1 bit.  This means that the bits before the first 1 bit are 0
  bits.  This means that when the complement is taken, all these 0 bits
  flip to 1 and the first 1 bit flips to 0.  Adding 1 means that the 1
  carries over all the way to the first 1 bit.  This means that while
  every other bit is flipped, the bits up to the least significant set
  bit are not.  So when we take a bitwise AND, we preserve only the
  least significant set bit.  Then, if we subtract 1 from this, we clear
  the least significant set bit and set all the bits before it to 1.  If
  we count how many 1 bits there are then we find the index of the least
  significant set bit.


* 2. Move Generation
** 2.1 Leaper Pieces
*** U64 mask_pawn_attacks(int square, int color);

  The function mask_pawn_attacks returns an attack mask that indicates
  where a pawn of the given color on the given square can attack.
  This attack mask is determined from the position of the pawn and the
  color it is.  If it is white, then we need to apply right shift
  (move towards rank 8), if it is black, we need to apply left shift
  (move towards rank 1).  We need some guard clauses to prevent
  invalid attacks if our pawns are on the "a" or "h" files.

*** U64 mask_knight_attacks(int square);

  The function mask_knight_attacks returns an attack mask that
  indicates where a knight on the given square can attack.  The attack
  mask is generated relative to the bit that the knight is on in a
  bitboard.  Guard clauses are needed to prevent knights on files "a"
  and "b" as well as "g" and "h" from making invalid attacks.

*** U64 mask_king_attacks(int square);

  The function mask_king_attacks returns an attack mask indicating
  where a king on the given square can attack.  The attack mask is
  generated based on the bit that the king is on in the bitboard.
  Guard clauses are needed to prevent kings on the "a" and "h" files
  from making certain illegal attacks.

** 2.2 Sliding Pieces
*** U64 mask_bishop_attacks(int square);

  The function mask_bishop_attacks returns a U64 attack mask with the
  bits representing the squares that a bishop on the given square
  could attack, given that there are no blocking pieces.
  
*** U64 generate_bishop_attacks(int square, U64 board);

  + param int square: The square that the bishop is on
  
  + param U64 board: Set bits indicate that there is a piece on the
    square that the bit represents
    
  + returns: A U64 mask of bits representing the squares that the
    bishop at the given square can target. If a set bit on U64 board
    would block the bishop's sliding attack path, the bits after the
    blocking piece will not be set in the mask.

*** U64 mask_rook_attacks(int square);

  + param int square: The square that the rook is on

  + returns: A mask representing the squares that the rook on the
    given square could attack, given that there are no blocking pieces
  
*** U64 generate_rook_attacks(int square, U64 board);

  + param int square: The square that the rook is on

  + param U64 board: Set bits in U64 board represent blocking pieces

  + return: A U64 mask of bits representing the squares that the rook
    at the given square can target, considering the squares that are
    blocked as described in U64 board.

*** U64 set_occupancy(int index, int bits_in_mask, U64 attack_mask);

  + param int index:

  + param int bits_in_mask:

  + param U64 attack_mask:

  + return: 
